"""
Module 2: Mini-Problem Solver
==============================
Takes generated mini-problems (from Module 1) and solves them with a
(potentially different) model. This enables cross-model testing:
e.g., problems generated by Llama solved by DeepSeek.

Usage:
    python run_solve.py
    python run_solve.py model=deepseek data.input_path=generated_problems.csv
"""
import json
import logging

import hydra
from omegaconf import DictConfig, OmegaConf
from tqdm import tqdm
from typing import List, Dict

from utils import (
    set_all_seeds, ModelWrapper, PromptBuilder, DataHandler, ResultLogger,
    parse_json_response, validate_solution
)

logging.getLogger("vllm").setLevel(logging.ERROR)
logging.getLogger("transformers").setLevel(logging.ERROR)
log = logging.getLogger(__name__)


def solve_problems(
    problems: List[Dict],
    model: ModelWrapper,
    prompt_builder: PromptBuilder,
    cfg: DictConfig,
) -> List[Dict]:
    """
    Solve a list of problems. For each problem, the model generates solutions
    WITHOUT seeing the original solutions (to test genuine problem-solving).
    """
    results = []
    solve_mode = cfg.solve_mode

    for item in tqdm(problems, desc="Solving problems"):
        problem = item.get("problem", "")
        if not problem:
            continue

        result = {
            "problem": problem,
            "category": item.get("category", ""),
            "original_ordinary": item.get("ordinary_solution", ""),
            "original_creative": item.get("creative_solution", ""),
            "original_implausible": item.get("implausible_solution", ""),
        }

        if solve_mode == "all":
            conv = prompt_builder.build_conversation("solve", problem=problem)
            response = model.generate_single(conv)
            parsed = parse_json_response(response)

            if parsed:
                result["solved_ordinary"] = parsed.get("ordinary_solution", "")
                result["solved_creative"] = parsed.get("creative_solution", "")
                result["solved_implausible"] = parsed.get("implausible_solution", "")
            else:
                result["solved_ordinary"] = ""
                result["solved_creative"] = ""
                result["solved_implausible"] = ""
                result["_parse_error"] = True

        elif solve_mode == "ordinary_only":
            conv = prompt_builder.build_conversation("solve_ordinary_only", problem=problem)
            response = model.generate_single(conv)
            parsed = parse_json_response(response)
            result["solved_ordinary"] = parsed.get("ordinary_solution", "") if parsed else ""

        elif solve_mode == "creative_only":
            ordinary_hint = item.get("ordinary_solution", "common solution")
            conv = prompt_builder.build_conversation(
                "solve_creative_only",
                problem=problem,
                ordinary_hint=ordinary_hint,
            )
            response = model.generate_single(conv)
            parsed = parse_json_response(response)
            result["solved_creative"] = parsed.get("creative_solution", "") if parsed else ""

        # Validate solved solutions
        for sol_key in ["solved_ordinary", "solved_creative", "solved_implausible"]:
            if sol_key in result and result[sol_key]:
                val = validate_solution(
                    result[sol_key],
                    cfg.validation.solution_min_words,
                    cfg.validation.solution_max_words,
                )
                result[f"{sol_key}_valid"] = val["valid"]
                result[f"{sol_key}_wc"] = val["word_count"]

        results.append(result)

    return results


@hydra.main(version_base=None, config_path="configs", config_name="config-solve")
def main(cfg: DictConfig) -> None:
    """Main entry point for the Solver module."""
    log.info("=" * 60)
    log.info("MINI-PROBLEMS SOLVER")
    log.info("=" * 60)
    log.info("Configuration:\n" + OmegaConf.to_yaml(cfg))

    set_all_seeds(cfg.seed)

    # --- Load problems ---
    data_handler = DataHandler(cfg)
    problems = data_handler.load_problems()
    log.info(f"Loaded {len(problems)} problems to solve")

    # --- Init model & prompts ---
    model = ModelWrapper(cfg)
    prompt_builder = PromptBuilder(cfg.prompt_config_path, cfg.model.name)

    # --- Solve ---
    results = solve_problems(problems, model, prompt_builder, cfg)

    # --- Save & Log ---
    logger = ResultLogger(cfg)
    output_path = logger.save_to_csv(results)

    stats = {
        "total_solved": len(results),
        "parse_errors": sum(1 for r in results if r.get("_parse_error", False)),
    }
    log.info(f"Summary: {stats}")
    logger.log_to_wandb(stats, results, output_path, cfg)

    log.info("Solver finished successfully.")


if __name__ == "__main__":
    main()
